version: "3"

volumes:
  server_data:
    driver: local

services:
  server:
    image: buddyspencer/gickup:latest
    container_name: gickup
    volumes:
      - server_data:/backup
      - ${PWD}/conf.yml:/gickup/conf.yml
    command: ["/gickup/conf.yml"]
    environment:
      - TZ=Europe/London
    restart: always
